let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-11.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "JS Crash Course",
    price: 45,
    desc: "This is an awesome course.",
    img: "images/img-12.jpg",
  },
];
